strategy_configs:
  default_strategy:
    name: "Default DAST Strategy"
    description: "A default strategy for dynamic application security testing."
    steps:
      - name: "Reconnaissance"
        action: "Perform initial reconnaissance on the target application."
      - name: "Scanning"
        action: "Scan the application for vulnerabilities."
      - name: "Exploitation"
        action: "Attempt to exploit identified vulnerabilities."
  
  advanced_strategy:
    name: "Advanced DAST Strategy"
    description: "An advanced strategy incorporating machine learning for vulnerability detection."
    steps:
      - name: "Data Collection"
        action: "Collect data from previous scans and vulnerabilities."
      - name: "Machine Learning Analysis"
        action: "Analyze data using machine learning models to identify potential vulnerabilities."
      - name: "Targeted Scanning"
        action: "Perform targeted scans based on analysis results."
      - name: "Exploitation"
        action: "Attempt to exploit vulnerabilities identified in the targeted scan."