deepseek_r1:
  model_name: "DeepSeek R1"
  version: "1.0"
  description: "DeepSeek R1 is designed for reasoning tasks in penetration testing."
  parameters:
    max_tokens: 2048
    temperature: 0.7
    top_p: 0.9
    frequency_penalty: 0.5
    presence_penalty: 0.5
  training_data:
    source: "Custom datasets from various penetration testing scenarios."
    size: "50GB"
  performance_metrics:
    accuracy: "85%"
    f1_score: "0.82"
    precision: "0.80"
    recall: "0.84"
  deployment:
    endpoint: "http://localhost:5000/deepseek_r1"
    timeout: 30
  logging:
    level: "INFO"
    file: "logs/deepseek_r1.log"