version: '3.8'

services:
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.ai-agents
    volumes:
      - ./orchestrator:/app/orchestrator
      - ./config:/app/config
    environment:
      - ORCHESTRATOR_CONFIG=/app/config/orchestrator/orchestrator_config.yaml

  ai_agents:
    build:
      context: .
      dockerfile: Dockerfile.ai-agents
    volumes:
      - ./ai_agents:/app/ai_agents
      - ./config:/app/config
    environment:
      - AI_MODELS_CONFIG=/app/config/ai_models

  execution_engine:
    build:
      context: .
      dockerfile: Dockerfile.execution-engine
    volumes:
      - ./execution_engine:/app/execution_engine
      - ./config:/app/config
    environment:
      - TOOL_CONFIG=/app/config/execution/tool_configs.yaml

  backend:
    build:
      context: .
      dockerfile: Dockerfile.execution-engine
    volumes:
      - ./backend:/app/backend
      - ./config:/app/config
    environment:
      - BACKEND_CONFIG=/app/config/backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.execution-engine
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"

networks:
  default:
    driver: bridge